services:
  chanchito:
    build: .
    ports:
      - "3000:3000"
    links:
      - monguito
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fede
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    # - otro-volumen:/otro/path
    # - mysql:/var/lib/mysql
    # - postgres:/var/lib/postgresql/data
volumes:
  mongo-data:
# otro-volumen:
# mysql:
# postgres
