services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fede
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
volumes:
  data:
